"""
Tutorial 14: Sandbox code execution, security policy, docker.

Demonstrates local Docker and remote TCP Docker sandbox usage.

Run:
  python tutorials/14_sandbox_code_exec.py
"""

import asyncio

from alphora.sandbox import Sandbox
from alphora.sandbox.types import ResourceLimits, SecurityPolicy


async def local_docker_example() -> None:
    """Local Docker sandbox example."""
    limits = ResourceLimits.minimal()
    policy = SecurityPolicy.strict()

    async with Sandbox(
        runtime="docker",
        workspace_root="/tmp/sandbox-tutorial",
        mount_mode="direct",
        resource_limits=limits,
        security_policy=policy,
    ) as sandbox:
        result = await sandbox.execute_code(
            "print('Hello from sandbox')\n"
            "x = 6 * 7\n"
            "print('x =', x)\n"
        )

        print("=== Execution Result ===")
        print("stdout:", result.stdout.strip())
        print("stderr:", result.stderr.strip())

        await sandbox.write_file("note.txt", "sandbox file content")
        files = await sandbox.list_files()

        print("\n=== Files ===")
        for f in files:
            print(f"- {f.path} (dir={f.is_directory}, size={f.size})")

        print("\n=== Container Path Structure ===")
        result = await sandbox.execute_shell("ls -la /mnt/workspace/")
        print(result.stdout)


async def remote_docker_example() -> None:
    """Remote Docker (TCP) sandbox example.

    Connects to a remote Docker daemon and executes code there.
    Requires:
      - A remote server with Docker daemon exposed on TCP
      - The image pre-built on the remote server
    """
    async with Sandbox(
        runtime="docker",
        docker_host="tcp://your-server:2375",
        workspace_root="/data/sandboxes/tutorial",
        skill_host_path="./skills",
        image="alphora-sandbox:latest",
    ) as sandbox:
        result = await sandbox.execute_code("import sys; print(sys.version)")
        print("Remote Python version:", result.stdout.strip())

        result = await sandbox.execute_shell("ls /mnt/workspace/")
        print("Workspace contents:", result.stdout.strip())

        result = await sandbox.execute_shell("ls /mnt/skills/ 2>/dev/null || echo '(empty)'")
        print("Skills contents:", result.stdout.strip())

        await sandbox.write_file("outputs/result.txt", "Generated by remote sandbox")
        content = await sandbox.read_file("outputs/result.txt")
        print("Read back:", content)


async def main() -> None:
    print("=" * 50)
    print("Local Docker Sandbox")
    print("=" * 50)
    await local_docker_example()

    # Uncomment to test remote Docker (update docker_host and workspace_root first):
    # print("\n" + "=" * 50)
    # print("Remote Docker Sandbox")
    # print("=" * 50)
    # await remote_docker_example()


if __name__ == "__main__":
    asyncio.run(main())
